const state = { tables: [], overview: null, current: null, rows: [], total: 0, page: 0, limit: 50, search: '', editing: null };
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const api = async (path, options = {}) => { const response = await fetch(`/api/v1${path}`, { ...options, headers: { ...(options.body ? {'content-type':'application/json'} : {}), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error?.message || '请求失败'); return data; };

async function boot() { try { const [overview, tables] = await Promise.all([api('/admin/overview'), api('/admin/tables')]); state.overview = overview.overview; state.tables = tables.tables; renderOverview(); renderNav(); const preferred = state.tables.find(item => item.name === 'projects') || state.tables[0]; if (preferred) await selectTable(preferred.name); } catch (error) { toast(error.message, true); } }
function renderOverview() { const o = state.overview; $('#overview').innerHTML = [['作品',o.counts.projects,'projects'],['片段',o.counts.segments,'segments'],['镜头',o.counts.shots,'segment_shots'],['媒体资产',o.counts.mediaAssets,o.mockMediaAssets ? `${o.mockMediaAssets} 条 Mock` : '已清理 Mock']].map(([label,value,foot],i) => `<article class="stat-card ${i===3 && o.mockMediaAssets ? 'warn' : i===3 ? 'good' : ''}"><span class="stat-label">${label}</span><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></article>`).join(''); }
function renderNav() { $('#table-nav').innerHTML = `<div class="nav-section">DATABASE</div>` + state.tables.map(table => `<button class="nav-item ${state.current?.name === table.name ? 'active' : ''}" data-table="${esc(table.name)}"><span>${esc(table.label)}</span><span class="count">${table.count}</span></button>`).join(''); document.querySelectorAll('[data-table]').forEach(button => button.addEventListener('click', () => selectTable(button.dataset.table))); }
async function selectTable(name) { state.current = state.tables.find(table => table.name === name); state.page = 0; state.search = ''; $('#search-input').value = ''; renderNav(); await loadRows(); }
async function loadRows() { if (!state.current) return; try { const params = new URLSearchParams({limit: state.limit, offset: state.page * state.limit}); if (state.search) params.set('search', state.search); const data = await api(`/admin/tables/${encodeURIComponent(state.current.name)}?${params}`); state.rows = data.rows; state.total = data.total; state.current = data.table; renderTable(); } catch(error) { toast(error.message, true); } }
function renderTable() { const table = state.current; $('#table-title').textContent = table.label; $('#table-meta').textContent = `${table.name} · 共 ${state.total} 条 · 第 ${state.page + 1} / ${Math.max(1,Math.ceil(state.total / state.limit))} 页 · 主键：${table.primaryKey}`; $('#data-head').innerHTML = `<tr>${table.columns.map(column => `<th>${esc(column.name)}</th>`).join('')}<th>操作</th></tr>`; $('#data-body').innerHTML = state.rows.map(row => `<tr>${table.columns.map(column => `<td>${cell(row[column.name], column)}</td>`).join('')}<td><div class="row-actions"><button class="mini-button" data-edit="${esc(String(row[table.primaryKey]))}">编辑</button><button class="mini-button danger" data-delete="${esc(String(row[table.primaryKey]))}">删除</button></div></td></tr>`).join(''); $('#empty-state').classList.toggle('hidden', state.rows.length > 0); document.querySelectorAll('[data-edit]').forEach(button => button.addEventListener('click', () => openEditor(button.dataset.edit))); document.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click', () => deleteRow(button.dataset.delete))); }
function cell(value, column) { if (value === null || value === undefined) return '<span class="cell-content" style="color:#adb7c5">NULL</span>'; const text = typeof value === 'object' ? JSON.stringify(value) : String(value); const isJson = /_json$/i.test(column.name) || /^[\[{]/.test(text.trim()); return `<span class="cell-content ${isJson ? 'json-cell' : ''} ${/id$|_id$|created_at|updated_at/i.test(column.name) ? 'mono' : ''}" title="${esc(text)}">${esc(text)}</span>`; }
function openEditor(key) { const row = state.rows.find(item => String(item[state.current.primaryKey]) === String(key)); if (!row) return; state.editing = {key, row}; $('#modal-eyebrow').textContent = state.current.name.toUpperCase(); $('#modal-title').textContent = `编辑 · ${state.current.label}`; $('#form-hint').textContent = `主键 ${state.current.primaryKey} = ${key} · 主键不可修改`; $('#form-fields').innerHTML = state.current.columns.map(column => { const value = row[column.name]; const text = value === null || value === undefined ? '' : String(value); const disabled = column.name === state.current.primaryKey ? 'disabled' : ''; const json = /_json$/i.test(column.name); return `<div class="field ${json || text.length > 130 ? 'full' : ''}"><label>${esc(column.name)} <small>${esc(column.type)}${column.nullable ? ' · 可空' : ''}</small></label>${json || text.length > 130 ? `<textarea data-field="${esc(column.name)}" ${disabled}>${esc(text)}</textarea>` : `<input data-field="${esc(column.name)}" value="${esc(text)}" ${disabled} />`}</div>`; }).join(''); $('#modal-backdrop').classList.remove('hidden'); }
async function saveRow() { if (!state.editing) return; const payload = {}; document.querySelectorAll('[data-field]').forEach(field => { if (!field.disabled) payload[field.dataset.field] = field.value; }); try { await api(`/admin/tables/${encodeURIComponent(state.current.name)}/${encodeURIComponent(state.editing.key)}`, {method:'PATCH',body:JSON.stringify(payload)}); closeModal(); toast('记录已保存'); await refreshCurrent(); } catch(error) { toast(error.message, true); } }
async function deleteRow(key) { if (!confirm(`确定删除 ${state.current.label} 中主键为 ${key} 的记录吗？此操作不可撤销。`)) return; try { await api(`/admin/tables/${encodeURIComponent(state.current.name)}/${encodeURIComponent(key)}`, {method:'DELETE'}); toast('记录已删除'); await refreshAll(); } catch(error) { toast(error.message, true); } }
async function refreshCurrent() { await loadRows(); const table = state.tables.find(item => item.name === state.current.name); if (table) table.count = state.total; }
async function refreshAll() { const selected = state.current?.name; const [overview, tables] = await Promise.all([api('/admin/overview'), api('/admin/tables')]); state.overview = overview.overview; state.tables = tables.tables; renderOverview(); renderNav(); if (selected) await selectTable(selected); }
function closeModal() { state.editing = null; $('#modal-backdrop').classList.add('hidden'); }
let toastTimer; function toast(message, error = false) { const node = $('#toast'); node.textContent = message; node.className = `toast show${error ? ' error' : ''}`; clearTimeout(toastTimer); toastTimer = setTimeout(() => node.className = 'toast', 2800); }
$('#refresh-all').addEventListener('click', () => refreshAll().catch(error => toast(error.message, true)));
$('#search-input').addEventListener('input', event => { clearTimeout(window.__searchTimer); window.__searchTimer = setTimeout(() => { state.search = event.target.value.trim(); state.page = 0; loadRows(); }, 250); });
$('#prev-page').addEventListener('click', () => { if (state.page > 0) { state.page -= 1; loadRows(); } });
$('#next-page').addEventListener('click', () => { if ((state.page + 1) * state.limit < state.total) { state.page += 1; loadRows(); } });
$('#close-modal').addEventListener('click', closeModal); $('#cancel-modal').addEventListener('click', closeModal); $('#modal-backdrop').addEventListener('click', event => { if (event.target.id === 'modal-backdrop') closeModal(); }); $('#save-row').addEventListener('click', saveRow);
$('#open-sql-help').addEventListener('click', () => alert('数据库文件：data/wenying.sqlite\n\n建议通过本后台修改记录。直接编辑 SQLite 前请先停止服务并备份数据库。\n\nJSON 字段可以直接在编辑框中修改，但必须保持合法 JSON。'));
boot();
